// OTOMATİK ÜRETİLDİ — elle düzenlemeyin.
// Yenilemek için: bun run catalog   (scripts/build-catalog.mjs)
// Kaynaklar: fluent-svelte-extra@2.2.5 + https://openani.me
// Üretim tarihi: 2026-08-02

export interface TokenInfo {
	name: string;
	group: string;
	/** Moddan bağımsız varsayılan (theme.css :root). */
	root?: string;
	/** .fds-theme-light altındaki varsayılan. */
	light?: string;
	/** .fds-theme-dark altındaki varsayılan. */
	dark?: string;
}

/** fluent-svelte-extra'nın resmi tema token'ları. */
export const FDS_TOKENS: TokenInfo[] = [
	{
		"name": "--fds-accent-base",
		"group": "Accent Colors",
		"root": "206, 100%, 42%"
	},
	{
		"name": "--fds-accent-dark-1",
		"group": "Accent Colors",
		"root": "209, 100%, 36%"
	},
	{
		"name": "--fds-accent-dark-2",
		"group": "Accent Colors",
		"root": "215, 100%, 29%"
	},
	{
		"name": "--fds-accent-dark-3",
		"group": "Accent Colors",
		"root": "226, 100%, 20%"
	},
	{
		"name": "--fds-accent-default",
		"group": "Accent",
		"light": "hsl(var(--fds-accent-dark-1))",
		"dark": "hsla(var(--fds-accent-light-2))"
	},
	{
		"name": "--fds-accent-disabled",
		"group": "Accent",
		"light": "hsla(0, 0%, 0%, 21.69%)",
		"dark": "hsla(0, 0%, 100%, 15.81%)"
	},
	{
		"name": "--fds-accent-light-1",
		"group": "Accent Colors",
		"root": "205, 100%, 49%"
	},
	{
		"name": "--fds-accent-light-2",
		"group": "Accent Colors",
		"root": "199, 99%, 69%"
	},
	{
		"name": "--fds-accent-light-3",
		"group": "Accent Colors",
		"root": "191, 98%, 80%"
	},
	{
		"name": "--fds-accent-secondary",
		"group": "Accent",
		"light": "hsla(var(--fds-accent-dark-1), 90%)",
		"dark": "hsla(var(--fds-accent-light-2), 90%)"
	},
	{
		"name": "--fds-accent-tertiary",
		"group": "Accent",
		"light": "hsla(var(--fds-accent-dark-1), 80%)",
		"dark": "hsla(var(--fds-accent-light-2), 80%)"
	},
	{
		"name": "--fds-accent-text-disabled",
		"group": "Accent Text",
		"light": "hsla(0, 0%, 0%, 36.14%)",
		"dark": "hsla(0, 0%, 100%, 36.28%)"
	},
	{
		"name": "--fds-accent-text-primary",
		"group": "Accent Text",
		"light": "hsl(var(--fds-accent-dark-2))",
		"dark": "hsl(var(--fds-accent-light-3))"
	},
	{
		"name": "--fds-accent-text-secondary",
		"group": "Accent Text",
		"light": "hsl(var(--fds-accent-dark-3))",
		"dark": "hsl(var(--fds-accent-light-3))"
	},
	{
		"name": "--fds-accent-text-tertiary",
		"group": "Accent Text",
		"light": "hsl(var(--fds-accent-dark-1))",
		"dark": "hsl(var(--fds-accent-light-2))"
	},
	{
		"name": "--fds-acrylic-background-base",
		"group": "Acrylic Background",
		"light": "transparent, rgba(243, 243, 243, 90%)",
		"dark": "linear-gradient(0deg, rgb(32, 32, 32, 50%), rgb(32, 32, 32, 50%)), rgba(32, 32, 32, 96%)"
	},
	{
		"name": "--fds-acrylic-background-default",
		"group": "Acrylic Background",
		"light": "transparent, rgba(252, 252, 252, 85%)",
		"dark": "linear-gradient(0deg, rgb(44, 44, 44, 15%), rgb(44, 44, 44, 15%)), rgba(44, 44, 44, 96%)"
	},
	{
		"name": "--fds-acrylic-blur-factor",
		"group": "Acrylic",
		"root": "blur(60px)"
	},
	{
		"name": "--fds-acrylic-fallback-background-base",
		"group": "Acrylic Background",
		"light": "hsla(0, 0%, 100%, 80%)",
		"dark": "hsla(0, 0%, 15%, 80%)"
	},
	{
		"name": "--fds-acrylic-fallback-filter",
		"group": "Acrylic",
		"root": "blur(32px) saturate(200%)"
	},
	{
		"name": "--fds-acrylic-noise-asset",
		"group": "Acrylic",
		"root": "url(\"data:image/png"
	},
	{
		"name": "--fds-acrylic-noise-asset-alpha",
		"group": "Acrylic",
		"root": "url(\"data:image/png"
	},
	{
		"name": "--fds-active-window-shadow",
		"group": "Shell Shadows",
		"light": "0px 32px 64px hsla(0, 0%, 0%, 28%), 0px 2px 21px hsla(0, 0%, 0%, 22%)",
		"dark": "0px 32px 64px hsla(0, 0%, 0%, 0.56), 0px 2px 21px hsla(0, 0%, 0%, 0.55)"
	},
	{
		"name": "--fds-body-font-size",
		"group": "Font Size",
		"root": "14px"
	},
	{
		"name": "--fds-body-large-font-size",
		"group": "Font Size",
		"root": "18px"
	},
	{
		"name": "--fds-caption-font-size",
		"group": "Font Size",
		"root": "12px"
	},
	{
		"name": "--fds-card-background-default",
		"group": "Card Background",
		"light": "hsla(0, 0%, 100%, 70%)",
		"dark": "hsla(0, 0%, 100%, 5.12%)"
	},
	{
		"name": "--fds-card-background-secondary",
		"group": "Card Background",
		"light": "hsla(0, 0%, 96%, 50%)",
		"dark": "hsla(0, 0%, 100%, 3.26%)"
	},
	{
		"name": "--fds-card-shadow",
		"group": "Shadows",
		"light": "0px 2px 4px hsla(0, 0%, 0%, 4%)",
		"dark": "0px 2px 4px hsla(0, 0%, 0%, 0.13)"
	},
	{
		"name": "--fds-card-stroke-default",
		"group": "Card Stroke",
		"light": "hsla(0, 0%, 0%, 5.78%)",
		"dark": "hsla(0, 0%, 0%, 10%)"
	},
	{
		"name": "--fds-card-stroke-default-solid",
		"group": "Card Stroke",
		"light": "hsl(0, 0%, 92%)",
		"dark": "hsl(0, 0%, 11%)"
	},
	{
		"name": "--fds-control-alt-fill-disabled",
		"group": "Control Alt Fill",
		"light": "var(--fds-control-alt-fill-transparent)",
		"dark": "var(--fds-control-fill-transparent)"
	},
	{
		"name": "--fds-control-alt-fill-quarternary",
		"group": "Control Alt Fill",
		"light": "hsla(0, 0%, 0%, 9.24%)",
		"dark": "hsla(0, 0%, 100%, 0.07)"
	},
	{
		"name": "--fds-control-alt-fill-secondary",
		"group": "Control Alt Fill",
		"light": "hsla(0, 0%, 0%, 2.41%)",
		"dark": "hsla(0, 0%, 0%, 0.1)"
	},
	{
		"name": "--fds-control-alt-fill-tertiary",
		"group": "Control Alt Fill",
		"light": "hsla(0, 0%, 0%, 5.78%)",
		"dark": "hsla(0, 0%, 100%, 0.042)"
	},
	{
		"name": "--fds-control-alt-fill-transparent",
		"group": "Control Alt Fill",
		"light": "transparent",
		"dark": "transparent"
	},
	{
		"name": "--fds-control-border-default",
		"group": "Borders",
		"light": "var(--fds-control-stroke-default) var(--fds-control-stroke-default) var(--fds-control-stroke-seconda…",
		"dark": "var(--fds-control-stroke-secondary) var(--fds-control-stroke-default) var(--fds-control-stroke-defau…"
	},
	{
		"name": "--fds-control-corner-radius",
		"group": "Roundness",
		"root": "4px"
	},
	{
		"name": "--fds-control-fast-duration",
		"group": "Duration",
		"root": "167ms"
	},
	{
		"name": "--fds-control-fast-out-slow-in-easing",
		"group": "Easing",
		"root": "cubic-bezier(0, 0, 0, 1)"
	},
	{
		"name": "--fds-control-faster-duration",
		"group": "Duration",
		"root": "83ms"
	},
	{
		"name": "--fds-control-fill-default",
		"group": "Control Fill",
		"light": "hsla(0, 0%, 100%, 70%)",
		"dark": "hsla(0, 0%, 100%, 0.061)"
	},
	{
		"name": "--fds-control-fill-disabled",
		"group": "Control Fill",
		"light": "var(--fds-control-fill-tertiary)",
		"dark": "hsla(0, 0%, 100%, 0.042)"
	},
	{
		"name": "--fds-control-fill-input-active",
		"group": "Control Fill",
		"light": "hsl(0, 0%, 100%)",
		"dark": "hsla(0, 0%, 12%, 70%)"
	},
	{
		"name": "--fds-control-fill-secondary",
		"group": "Control Fill",
		"light": "hsla(0, 0%, 98%, 50%)",
		"dark": "hsla(0, 0%, 100%, 0.084)"
	},
	{
		"name": "--fds-control-fill-tertiary",
		"group": "Control Fill",
		"light": "hsla(0, 0%, 98%, 30%)",
		"dark": "hsla(0, 0%, 100%, 0.033)"
	},
	{
		"name": "--fds-control-fill-transparent",
		"group": "Control Fill",
		"light": "transparent",
		"dark": "transparent"
	},
	{
		"name": "--fds-control-normal-duration",
		"group": "Duration",
		"root": "250ms"
	},
	{
		"name": "--fds-control-on-image-fill-default",
		"group": "Control on Image Fill",
		"light": "hsla(0, 0%, 100%, 79%)",
		"dark": "hsla(0, 0%, 11%, 70%)"
	},
	{
		"name": "--fds-control-on-image-fill-disabled",
		"group": "Control on Image Fill",
		"light": "transparent",
		"dark": "transparent"
	},
	{
		"name": "--fds-control-on-image-fill-secondary",
		"group": "Control on Image Fill",
		"light": "hsl(0, 0%, 95%)",
		"dark": "hsl(0, 0%, 10%)"
	},
	{
		"name": "--fds-control-on-image-fill-tertiary",
		"group": "Control on Image Fill",
		"light": "hsl(0, 0%, 92%)",
		"dark": "hsl(0, 0%, 7%)"
	},
	{
		"name": "--fds-control-slow-duration",
		"group": "Duration",
		"root": "333ms"
	},
	{
		"name": "--fds-control-solid-fill-default",
		"group": "Control Solid Fill",
		"light": "hsl(0, 0%, 100%)",
		"dark": "hsl(0, 0%, 27%)"
	},
	{
		"name": "--fds-control-stroke-default",
		"group": "Control Stroke",
		"light": "hsla(0, 0%, 0%, 5.78%)",
		"dark": "hsla(0, 0%, 100%, 6.98%)"
	},
	{
		"name": "--fds-control-stroke-on-accent-default",
		"group": "Control Stroke on Accent",
		"light": "hsla(0, 0%, 100%, 8%)",
		"dark": "hsla(0, 0%, 100%, 8%)"
	},
	{
		"name": "--fds-control-stroke-on-accent-disabled",
		"group": "Control Stroke on Accent",
		"light": "var(--fds-control-stroke-on-accent-default)",
		"dark": "hsla(0, 0%, 0%, 20%)"
	},
	{
		"name": "--fds-control-stroke-on-accent-secondary",
		"group": "Control Stroke on Accent",
		"light": "hsla(0, 0%, 0%, 40%)",
		"dark": "hsla(0, 0%, 0%, 14%)"
	},
	{
		"name": "--fds-control-stroke-on-accent-tertiary",
		"group": "Control Stroke on Accent",
		"light": "hsla(0, 0%, 0%, 21.69%)",
		"dark": "hsla(0, 0%, 0%, 21.69%)"
	},
	{
		"name": "--fds-control-stroke-secondary",
		"group": "Control Stroke",
		"light": "hsla(0, 0%, 0%, 16.22%)",
		"dark": "hsla(0, 0%, 100%, 9.3%)"
	},
	{
		"name": "--fds-control-strong-fill-default",
		"group": "Control Strong Fill",
		"light": "hsla(0, 0%, 0%, 44.58%)",
		"dark": "hsla(0, 0%, 100%, 54.42%)"
	},
	{
		"name": "--fds-control-strong-fill-disabled",
		"group": "Control Strong Fill",
		"light": "hsla(0, 0%, 0%, 31.73%)",
		"dark": "hsla(0, 0%, 100%, 24.65%)"
	},
	{
		"name": "--fds-control-strong-stroke-default",
		"group": "Control Strong Stroke",
		"light": "hsla(0, 0%, 0%, 44.58%)",
		"dark": "hsla(0, 0%, 100%, 54.42%)"
	},
	{
		"name": "--fds-control-strong-stroke-disabled",
		"group": "Control Strong Stroke",
		"light": "hsla(0, 0%, 0%, 21.69%)",
		"dark": "hsla(0, 0%, 100%, 15.81%)"
	},
	{
		"name": "--fds-control-strong-stroke-on-image-default",
		"group": "Control Strong Stroke on Image",
		"light": "hsla(0, 0%, 100%, 35%)",
		"dark": "hsla(0, 0%, 0%, 42%)"
	},
	{
		"name": "--fds-dialog-shadow",
		"group": "Shadows",
		"light": "0px 32px 64px hsla(0, 0%, 0%, 18.76%), 0px 2px 21px hsl(0, 0%, 0%, 14.74%)",
		"dark": "0px 32px 64px hsla(0, 0%, 0%, 0.37), 0px 2px 21px hsla(0, 0%, 0%, 0.37)"
	},
	{
		"name": "--fds-display-font-size",
		"group": "Font Size",
		"root": "68px"
	},
	{
		"name": "--fds-divider-stroke-default",
		"group": "Divider Stroke",
		"light": "hsla(0, 0%, 0%, 8.03%)",
		"dark": "hsla(0, 0%, 100%, 8.37%)"
	},
	{
		"name": "--fds-flyout-shadow",
		"group": "Shadows",
		"light": "0px 8px 16px hsla(0, 0%, 0%, 14%)",
		"dark": "0px 8px 16px hsla(0, 0%, 0%, 0.14)"
	},
	{
		"name": "--fds-focus-stroke",
		"group": "Focus Stroke",
		"root": "0 0 0 1px var(--fds-focus-stroke-inner), 0 0 0 3px var(--fds-focus-stroke-outer)"
	},
	{
		"name": "--fds-focus-stroke-inner",
		"group": "Focus Stroke",
		"light": "hsl(0, 0%, 100%)",
		"dark": "hsla(0, 0%, 0%, 70%)"
	},
	{
		"name": "--fds-focus-stroke-outer",
		"group": "Focus Stroke",
		"light": "hsla(0, 0%, 0%, 89.56%)",
		"dark": "hsl(0, 0%, 100%)"
	},
	{
		"name": "--fds-font-family-display",
		"group": "Font Families",
		"root": "\"Segoe UI Variable Display\", \"Seoge UI Variable Static Display\", var(--fds-font-family-fallback)"
	},
	{
		"name": "--fds-font-family-fallback",
		"group": "Font Families",
		"root": "\"Segoe UI\", -apple-system, ui-sans-serif, system-ui, BlinkMacSystemFont, Helvetica, Arial, sans-serif"
	},
	{
		"name": "--fds-font-family-small",
		"group": "Font Families",
		"root": "\"Segoe UI Variable Small\", \"Seoge UI Variable Static Small\", var(--fds-font-family-fallback)"
	},
	{
		"name": "--fds-font-family-text",
		"group": "Font Families",
		"root": "\"Segoe UI Variable Text\", \"Seoge UI Variable Static Text\", var(--fds-font-family-fallback)"
	},
	{
		"name": "--fds-inactive-window-shadow",
		"group": "Shell Shadows",
		"light": "0px 16px 32px hsla(0, 0%, 0%, 18%), 0px 2px 10.67px hsla(0, 0%, 0%, 0.1474)",
		"dark": "0px 16px 32px hsla(0, 0%, 0%, 0.37), 0px 2px 10.67px hsla(0, 0%, 0%, 0.37)"
	},
	{
		"name": "--fds-layer-background-alt",
		"group": "Layer",
		"light": "hsl(0, 0%, 100%)",
		"dark": "hsla(0, 0%, 100%, 5.38%)"
	},
	{
		"name": "--fds-layer-background-default",
		"group": "Layer",
		"light": "hsla(0, 0%, 100%, 50%)",
		"dark": "hsla(0, 0%, 23%, 30%)"
	},
	{
		"name": "--fds-layer-on-accent-acrylic-background-default",
		"group": "Layer on Acrylic",
		"light": "var(--fds-layer-on-acrylic-background-default)"
	},
	{
		"name": "--fds-layer-on-accent-background-default",
		"group": "Layer on Acrylic",
		"dark": "var(--fds-layer-on-acrylic-background-default)"
	},
	{
		"name": "--fds-layer-on-acrylic-background-default",
		"group": "Layer on Acrylic",
		"light": "hsla(0, 0%, 100%, 25%)",
		"dark": "hsla(0, 0%, 100%, 3.59%)"
	},
	{
		"name": "--fds-overlay-corner-radius",
		"group": "Roundness",
		"root": "8px"
	},
	{
		"name": "--fds-smoke-background-default",
		"group": "Smoke Background",
		"light": "hsla(0, 0%, 0%, 30%)",
		"dark": "hsla(0, 0%, 0%, 30%)"
	},
	{
		"name": "--fds-solid-background-base",
		"group": "Solid Background",
		"light": "hsl(0, 0%, 95%)",
		"dark": "hsl(0, 0%, 13%)"
	},
	{
		"name": "--fds-solid-background-quarternary",
		"group": "Solid Background",
		"light": "hsl(0, 0%, 100%)",
		"dark": "hsl(0, 0%, 17%)"
	},
	{
		"name": "--fds-solid-background-secondary",
		"group": "Solid Background",
		"light": "hsl(0, 0%, 93%)",
		"dark": "hsl(0, 0%, 11%)"
	},
	{
		"name": "--fds-solid-background-tertiary",
		"group": "Solid Background",
		"light": "hsl(0, 0%, 98%)",
		"dark": "hsl(0, 0%, 16%)"
	},
	{
		"name": "--fds-subtitle-font-size",
		"group": "Font Size",
		"root": "20px"
	},
	{
		"name": "--fds-subtle-fill-disabled",
		"group": "Subtle Fill",
		"light": "var(--fds-subtle-fill-transparent)",
		"dark": "transparent"
	},
	{
		"name": "--fds-subtle-fill-secondary",
		"group": "Subtle Fill",
		"light": "hsla(0, 0%, 0%, 3.73%)",
		"dark": "hsla(0, 0%, 100%, 6.05%)"
	},
	{
		"name": "--fds-subtle-fill-tertiary",
		"group": "Subtle Fill",
		"light": "hsla(0, 0%, 0%, 2.41%)",
		"dark": "hsla(0, 0%, 100%, 4.19%)"
	},
	{
		"name": "--fds-subtle-fill-transparent",
		"group": "Subtle Fill",
		"light": "transparent",
		"dark": "transparent"
	},
	{
		"name": "--fds-surface-stroke-default",
		"group": "Surface Stroke",
		"light": "hsla(0, 0%, 46%, 40%)",
		"dark": "hsla(0, 0%, 46%, 40%)"
	},
	{
		"name": "--fds-surface-stroke-flyout",
		"group": "Surface Stroke",
		"light": "hsla(0, 0%, 0%, 5.78%)",
		"dark": "hsla(0, 0%, 0%, 20%)"
	},
	{
		"name": "--fds-system-attention",
		"group": "System",
		"light": "hsl(209, 100%, 36%)",
		"dark": "hsl(199, 100%, 69%)"
	},
	{
		"name": "--fds-system-background-attention",
		"group": "System Background",
		"light": "hsla(0, 0%, 96%, 50%)",
		"dark": "hsla(0, 0%, 100%, 3.26%)"
	},
	{
		"name": "--fds-system-background-caution",
		"group": "System Background",
		"light": "hsl(47, 100%, 90%)",
		"dark": "hsl(40, 46%, 18%)"
	},
	{
		"name": "--fds-system-background-critical",
		"group": "System Background",
		"light": "hsl(355, 85%, 95%)",
		"dark": "hsl(2, 28%, 21%)"
	},
	{
		"name": "--fds-system-background-solid-attention",
		"group": "System Background Solid",
		"light": "hsl(0, 0%, 97%)",
		"dark": "hsl(0, 0%, 18%)"
	},
	{
		"name": "--fds-system-background-solid-neutral",
		"group": "System Background Solid",
		"light": "hsl(0, 0%, 95%)",
		"dark": "hsl(0, 0%, 62%)"
	},
	{
		"name": "--fds-system-background-success",
		"group": "System Background",
		"light": "hsl(115, 58%, 92%)",
		"dark": "hsl(67, 39%, 17%)"
	},
	{
		"name": "--fds-system-caution",
		"group": "System",
		"light": "hsl(36, 100%, 31%)",
		"dark": "hsl(54, 100%, 49%)"
	},
	{
		"name": "--fds-system-critical",
		"group": "System",
		"light": "hsl(5, 75%, 44%)",
		"dark": "hsl(354, 100%, 80%)"
	},
	{
		"name": "--fds-system-neutral",
		"group": "System",
		"light": "hsla(0, 0%, 0%, 44.58%)",
		"dark": "hsla(0, 0%, 100%, 54.42%)"
	},
	{
		"name": "--fds-system-solid-neutral",
		"group": "System Solid",
		"light": "hsl(0, 0%, 54%)",
		"dark": "hsl(0, 0%, 62%)"
	},
	{
		"name": "--fds-system-success",
		"group": "System",
		"light": "hsl(120, 78%, 27%)",
		"dark": "hsl(113, 51%, 58%)"
	},
	{
		"name": "--fds-text-disabled",
		"group": "Text",
		"light": "hsla(0, 0%, 0%, 36.14%)",
		"dark": "hsla(0, 0%, 100%, 36.28%)"
	},
	{
		"name": "--fds-text-on-accent-disabled",
		"group": "Text on Accent",
		"light": "var(--fds-text-on-accent-secondary)",
		"dark": "hsla(0, 0%, 100%, 0.53)"
	},
	{
		"name": "--fds-text-on-accent-primary",
		"group": "Text on Accent",
		"light": "hsl(0, 0%, 100%)",
		"dark": "hsl(0, 0%, 0%)"
	},
	{
		"name": "--fds-text-on-accent-secondary",
		"group": "Text on Accent",
		"light": "hsla(0, 0%, 100%, 70%)",
		"dark": "hsla(0, 0%, 0%, 0.5)"
	},
	{
		"name": "--fds-text-on-accent-selected",
		"group": "Text on Accent",
		"light": "var(--fds-text-on-accent-primary)",
		"dark": "hsl(0, 0%, 100%)"
	},
	{
		"name": "--fds-text-primary",
		"group": "Text",
		"light": "hsla(0, 0%, 0%, 89.56%)",
		"dark": "hsla(0, 0%, 100%, 100%)"
	},
	{
		"name": "--fds-text-secondary",
		"group": "Text",
		"light": "hsla(0, 0%, 0%, 60.63%)",
		"dark": "hsla(0, 0%, 100%, 78.6%)"
	},
	{
		"name": "--fds-text-tertiary",
		"group": "Text",
		"light": "hsla(0, 0%, 0%, 44.58%)",
		"dark": "hsla(0, 0%, 100%, 54.42%)"
	},
	{
		"name": "--fds-title-font-size",
		"group": "Font Size",
		"root": "28px"
	},
	{
		"name": "--fds-title-large-font-size",
		"group": "Font Size",
		"root": "40px"
	},
	{
		"name": "--fds-tooltip-shadow",
		"group": "Shadows",
		"light": "0px 4px 8px hsla(0, 0%, 0%, 14%)",
		"dark": "0px 4px 8px hsla(0, 0%, 0%, 0.26)"
	}
];

/** openani.me'nin CSS'inde geçen class isimleri (Svelte hash'leri ayıklandı). */
export const SITE_CLASSES: string[] = [
	"about-me",
	"about-me-input",
	"accent",
	"account-flyout",
	"acrylic",
	"acrylic-surface",
	"action-visible",
	"action-wrapped",
	"actions",
	"active",
	"admin",
	"after",
	"age-rating",
	"ai",
	"ai-button",
	"ai-mode-item",
	"ai-mode-selection-tip",
	"ai-mode-selection-transition",
	"ai-placeholder",
	"ai-recommendations-banner",
	"air",
	"alignment-center",
	"alignment-end",
	"alignment-start",
	"alt",
	"alt-giveaway",
	"anim-fly-in",
	"anim-wrap",
	"animated",
	"animation",
	"anime-avatar",
	"anime-card",
	"anime-desc",
	"anime-details",
	"anime-episode-list-dialog",
	"anime-grid",
	"anime-info",
	"anime-metadata",
	"anime-name",
	"anime-result",
	"anime-summary-banner",
	"animes",
	"animes-wrapper",
	"apply-offline-margin",
	"arrow",
	"attachment",
	"attachment-present",
	"attachments-container",
	"auth-dialog",
	"author",
	"auto-suggest-box",
	"auto-suggest-box-flyout",
	"auto-suggest-item-wrapper",
	"auto-width",
	"avatar",
	"avatar-container",
	"avatar-img",
	"avatar-spacer",
	"avatar-stack",
	"avatar-wrap",
	"back",
	"backdrop-blur-layer",
	"backdrop-overlay",
	"badge",
	"badges",
	"banned-participants-page",
	"banner",
	"banner-background",
	"banner-image",
	"banner-info",
	"bar",
	"bar-container",
	"bars",
	"beta-actions",
	"beta-copy",
	"beta-tag",
	"between",
	"bg-carousel",
	"bigger-svg",
	"blackout",
	"bloop-bg-canvas",
	"bloop-bg-pending",
	"bloop-bg-ready",
	"body",
	"body-inner",
	"bottom",
	"bottom-content",
	"bottom-control-transition",
	"bottom-controls",
	"bottom-drawer",
	"btn",
	"btn-inner",
	"bulk-actions",
	"bulk-bar",
	"button",
	"button-content",
	"button-group",
	"button-overlay",
	"buttons",
	"calendar-date-picker-icon",
	"calendar-date-picker-label",
	"calendar-view",
	"calendar-view-header",
	"calendar-view-header-text",
	"calendar-view-item",
	"calendar-view-pagination-controls",
	"calendar-view-table",
	"calendar-view-table-wrapper",
	"canvas-wrap",
	"card-actions",
	"card-cell",
	"card-content",
	"card-footer",
	"card-info",
	"card-meta",
	"card-status-bar",
	"card-title-row",
	"card-top",
	"card-wrapper",
	"categories",
	"center",
	"center-create",
	"center-flex",
	"center-header",
	"center-loading",
	"center-state",
	"center-warn",
	"center-warn-top",
	"center-wrap",
	"chart-container",
	"chart-tooltip",
	"chart-tooltip-body",
	"chart-tooltip-title",
	"chart-wrapper",
	"checkbox",
	"checkbox-container",
	"checkbox-glyph",
	"checkbox-grid",
	"checkbox-inner",
	"checkbox-item",
	"checked",
	"chip",
	"cinema-player",
	"click-handler",
	"clickable",
	"clip",
	"clip-icon",
	"cloudflare",
	"code-card",
	"code-list",
	"code-main",
	"code-row",
	"code-title-row",
	"col",
	"col-fs",
	"color-component",
	"color-picker",
	"color-preview",
	"color-selectors",
	"column-flex",
	"com",
	"combo-box",
	"combo-box-dropdown",
	"combo-box-icon",
	"combo-box-item",
	"combo-box-label",
	"combo-box-textbox",
	"command-section",
	"comment",
	"comment-gif",
	"comment-text-area",
	"comments",
	"comments-header",
	"comments-shadow-overlay",
	"completed-spacer",
	"connection",
	"connections",
	"contain",
	"container",
	"content",
	"content-area",
	"content-area-title",
	"content-dialog",
	"content-dialog-body",
	"content-dialog-container",
	"content-dialog-footer",
	"content-dialog-smoke",
	"content-dialog-title",
	"contents",
	"context-bottom",
	"context-menu-anchor",
	"context-menu-wrapper",
	"context-top",
	"contributions",
	"controls",
	"cover-banner",
	"created-code",
	"critical",
	"cropper-container",
	"cropperArea",
	"current",
	"currentEpisode",
	"currently-downloading",
	"custom-top",
	"danger",
	"darken",
	"dashed",
	"dec",
	"dec2",
	"decorated-avatar",
	"decoration",
	"decoration-container",
	"decorations",
	"decorations-wrap",
	"default-avatar",
	"delay-300",
	"delay-400",
	"delay-500",
	"delay-600",
	"delay-700",
	"delete-btn",
	"delete-overlay",
	"depth",
	"desc",
	"description",
	"desktop-setting-option",
	"detail-section",
	"details",
	"dialog-episodes",
	"dialog-episodes-list",
	"dialog-inner",
	"direction-bottom",
	"direction-center",
	"direction-down",
	"direction-top",
	"direction-up",
	"disabled",
	"disabled-interaction",
	"discord-invite",
	"discount-header",
	"divider",
	"do-not-use-transform",
	"download-btn-wrapper",
	"download-cards",
	"download-count",
	"download-icon",
	"download-item-card",
	"download-mode-item",
	"download-ring",
	"download-setsuki-wrap",
	"drag-badge",
	"drag-ghost",
	"drag-handle",
	"drag-icon",
	"drag-icon-wrapper",
	"drag-name",
	"dragger-absolute",
	"dragging",
	"drawer-overlay",
	"duration-group",
	"edit-about-me",
	"edit-overlay",
	"editable",
	"emoji",
	"emoji-wrapper",
	"emojified",
	"emojis",
	"empty-list",
	"empty-state",
	"encodes-main",
	"ended",
	"enhanced-badge",
	"enhanced-highlight",
	"entries",
	"ep-avatar-container",
	"ep-inf-small",
	"ep-info",
	"episode-card",
	"episode-header",
	"episode-info",
	"episode-item",
	"episodes",
	"episodes-container",
	"episodes-header",
	"episodes-shadow-overlay",
	"error",
	"error-badge",
	"error-wrap",
	"expand-menu",
	"expand-menu-closed",
	"expand-menu-icon",
	"expand-menu-text",
	"expand-section",
	"expandable",
	"expanded",
	"expander",
	"expander-chevron",
	"expander-content",
	"expander-content-anchor",
	"expander-control",
	"expander-header",
	"expander-header-title",
	"expander-icon",
	"expanders",
	"experimental-features",
	"expired",
	"extra-info",
	"fake-fullscreen",
	"fansub-inner",
	"fansub-item",
	"fansub-list",
	"fansub-members",
	"fansubs",
	"fds-checkbox",
	"fds-copy-calculation",
	"fds-theme-dark",
	"fds-theme-light",
	"feature-indicator",
	"feature-item",
	"feature-text",
	"features-list",
	"features-row",
	"field",
	"fill",
	"filler-badge",
	"filters",
	"first",
	"first-img",
	"first-item",
	"first-play-overlay",
	"fit",
	"flex",
	"flex-playlist",
	"flex-td",
	"flex-top",
	"flex-wrap-item",
	"flipper",
	"flipper-transition",
	"flipper-wrap",
	"floating",
	"flyout",
	"flyout-anchor",
	"flyout-backdrop",
	"flyout-footer",
	"flyout-menu",
	"flyout-open",
	"flyout-wrapper",
	"followers-dialog",
	"followers-dialog-container",
	"followers-dialog-user",
	"followers-dialog-user-info",
	"followers-following",
	"following-dialog",
	"following-dialog-container",
	"following-dialog-user",
	"following-dialog-user-info",
	"follows",
	"footer-buttons",
	"footer-logo",
	"form-grid",
	"four-k",
	"frame-animation",
	"frame-img",
	"frame-number",
	"frames",
	"fs",
	"full",
	"full-height",
	"fullWidth",
	"fullscreen",
	"fullscreen-and-first",
	"fullscreen-and-last",
	"fullscreen-icon",
	"fullscreen-player-container",
	"fullscreen-review-container",
	"fullscreened",
	"fw",
	"generated-list",
	"gif-picker",
	"giveaway-card",
	"giveaway-grid",
	"giveaway-info",
	"glob",
	"go-back",
	"gradient-button",
	"gradient-layer",
	"gradient-scene-hidden",
	"grid",
	"grid-view-item",
	"grid-wrap",
	"group-continues",
	"grouped",
	"groups",
	"handle",
	"header",
	"header-right",
	"header-section",
	"header-transition",
	"hero",
	"hidden",
	"hide",
	"hide-chevron",
	"highlighted",
	"hold",
	"horizontal",
	"horizontal-divider",
	"hoverable",
	"html5-video",
	"icon",
	"icon-button",
	"icon-wrapper",
	"iconify",
	"image",
	"image-container",
	"image-preview",
	"image-skeleton",
	"image-wrapper",
	"img-container",
	"indented",
	"indeterminate",
	"indicator-arrows",
	"indicator-content",
	"info",
	"info-badge",
	"info-bar",
	"info-bar-action",
	"info-bar-close-button",
	"info-bar-content",
	"info-bar-icon",
	"info-column",
	"inner",
	"inner-attachment",
	"inner-button",
	"inner-canvas-content",
	"inner-comments",
	"inner-dialog",
	"inner-download",
	"inner-episodes",
	"inner-flyout",
	"inner-footer",
	"inner-grid-item",
	"inner-header",
	"inner-top",
	"input",
	"input-grid",
	"input-wrapper",
	"input-wrapper-inner",
	"inputs",
	"is-zoomed",
	"isNative",
	"item",
	"item-actions",
	"item-checkbox",
	"item-details",
	"item-header",
	"item-info",
	"items",
	"items-root",
	"kanji",
	"label",
	"labels",
	"last",
	"last-item",
	"leader",
	"leaving",
	"left",
	"left-align",
	"left-bottom-content",
	"left-indicator",
	"left-info",
	"left-side",
	"left-triangles",
	"light",
	"likes",
	"list",
	"list-empty",
	"list-item",
	"load-btn",
	"load-more-wrapper",
	"loaded",
	"loading",
	"loading-player",
	"loading-right",
	"locked",
	"login-page",
	"logo",
	"logo-button",
	"logos",
	"lottie-player",
	"lottie-player-controls",
	"lottie-player-error",
	"ltr",
	"luts",
	"macos",
	"main-content-wrapper",
	"main-graphics",
	"main-info",
	"margin",
	"mascot-image-desktop",
	"mascot-image-mobile",
	"masked-content",
	"masonry",
	"media",
	"member-avatar",
	"member-card",
	"member-info",
	"members-list",
	"menu-bar",
	"menu-bar-item",
	"menu-flyout",
	"menu-flyout-anchor",
	"menu-flyout-backdrop",
	"menu-flyout-divider",
	"menu-flyout-item",
	"menu-flyout-item-arrow",
	"menu-flyout-item-bullet",
	"menu-flyout-item-checkmark",
	"menu-flyout-item-hint",
	"menu-flyout-item-input-label",
	"menu-flyout-submenu-anchor",
	"menu-flyout-surface-container",
	"menu-flyout-wrapper",
	"message",
	"message-wrapped",
	"messages",
	"meta-grid",
	"meta-item",
	"metadata",
	"metadata-wrap",
	"misc",
	"mobile",
	"mobile-animes-wrapper",
	"mobile-bottom-nav",
	"mobile-center-controls",
	"mobile-controls",
	"mobile-drawer-open",
	"mobile-episodes",
	"mobile-filter",
	"mobile-full-height-without-toolbar",
	"mobile-fullscreen-icon-button",
	"mobile-notification-btn",
	"mobile-notification-count",
	"mobile-notification-empty",
	"mobile-notification-list",
	"mobile-patches",
	"mobile-play-icon-button",
	"mobile-shadow-overlay",
	"mobile-topbar",
	"modal-content",
	"more-recs-item",
	"native",
	"native-app",
	"navigation-view",
	"navigation-view-page",
	"navigation-view-pane",
	"navigation-view-pane-header",
	"need-more-info",
	"new-playlist",
	"new-tomolist",
	"next-icon",
	"no-animation",
	"no-cursor",
	"no-padding",
	"no-pe",
	"no-select",
	"noise-container",
	"noise-img",
	"noise-overlay",
	"non-clickable",
	"not-fs",
	"not-fullscreen",
	"not-included",
	"note",
	"notice-body",
	"notice-title",
	"notification-btn-wrapper",
	"notification-card",
	"notification-cards",
	"notification-content",
	"notification-count",
	"notification-empty-wrap",
	"notification-icon",
	"notification-page-content",
	"notification-title-row",
	"nsfw-content-notice",
	"nufs-banner",
	"number-box",
	"number-box-spinner",
	"number-box-spinner-flyout",
	"o-h",
	"oauth-section",
	"opacity-handler",
	"opacity-transition",
	"open",
	"openanime-ass-handle",
	"openanime-scene-controller",
	"openanime-vanilla-player",
	"options",
	"orientation-horizontal",
	"orientation-vertical",
	"os-scrollbar",
	"os-scrollbar-auto-hide",
	"os-scrollbar-auto-hide-hidden",
	"os-scrollbar-cornerless",
	"os-scrollbar-handle",
	"os-scrollbar-handle-interactive",
	"os-scrollbar-horizontal",
	"os-scrollbar-interaction",
	"os-scrollbar-rtl",
	"os-scrollbar-track",
	"os-scrollbar-track-interactive",
	"os-scrollbar-transitionless",
	"os-scrollbar-unusable",
	"os-scrollbar-vertical",
	"os-scrollbar-visible",
	"os-scrollbar-wheel",
	"os-size-observer",
	"os-size-observer-appear",
	"os-size-observer-listener",
	"os-size-observer-listener-item",
	"os-size-observer-listener-item-final",
	"os-size-observer-listener-scroll",
	"os-theme-dark",
	"os-theme-light",
	"os-theme-none",
	"os-trinsic-observer",
	"other",
	"out-of-range",
	"outside",
	"outside-input",
	"overlay",
	"overlays",
	"page",
	"page-1",
	"page-2",
	"page-container",
	"page-content",
	"page-wrapper",
	"pagination-buttons",
	"pane",
	"panel-card",
	"participant-box",
	"participant-name",
	"participants-list",
	"participants-list-winners",
	"participants-page",
	"participants-wrap",
	"path-checkmark",
	"path-indeterminate",
	"peek",
	"peek-item",
	"people",
	"person-picture",
	"person-picture-badge",
	"person-picture-container",
	"pip-icon",
	"placeholder",
	"placeholder-text",
	"placement-",
	"placement-after",
	"placement-auto",
	"placement-before",
	"placement-bottom",
	"placement-left",
	"placement-right",
	"placement-top",
	"play-button",
	"player-episode-list-item",
	"player-item",
	"playlist-card",
	"playlist-flyout",
	"playlists",
	"popover",
	"popover-background",
	"popover-content",
	"popover-info",
	"popover-snapshot",
	"popular",
	"portal",
	"poster",
	"premium-badge",
	"premium-required",
	"preset",
	"preview",
	"previous-icon",
	"pricing-title",
	"profile-badge",
	"profile-badge-filter",
	"progress",
	"progress-alt",
	"progress-bar",
	"progress-bar-rail",
	"progress-bar-track",
	"progress-container",
	"progress-paused",
	"progress-ring",
	"property",
	"pt",
	"qr-inner",
	"qr-wrap",
	"quick-actions",
	"radio-button",
	"radio-button-container",
	"rating-wrapper",
	"ratings",
	"reasoning-container",
	"reasoning-line",
	"reasoning-wrapper",
	"recursive-cascaded",
	"redeem-card",
	"redeem-card-text",
	"redeem-dialog",
	"released-badge",
	"remove-container",
	"replies",
	"replies-controller",
	"replies-wrapper",
	"reply-col",
	"reply-container",
	"reply-indicator",
	"replying",
	"resolution-inner",
	"resolved",
	"result-card",
	"result-img",
	"result-info",
	"result-left",
	"result-row",
	"results",
	"reverse",
	"review",
	"review-content",
	"review-title",
	"reward-header",
	"reward-icon",
	"reward-info",
	"reward-item",
	"reward-meta",
	"reward-row",
	"rewards-list",
	"right",
	"right-align",
	"right-bottom-content",
	"right-buttons",
	"right-indicator",
	"right-side",
	"right-triangles",
	"ring",
	"ring-progress",
	"ring-track",
	"ripple-animate",
	"room-name",
	"room-page",
	"root",
	"rotation",
	"round",
	"row",
	"rtl",
	"safe",
	"scale-to-height",
	"scene-inner-content",
	"scenes",
	"score",
	"scroll",
	"scroll-container",
	"scrollbar-disabled",
	"search",
	"search-container",
	"search-icon",
	"search-overlay",
	"search-page",
	"search-progress",
	"search-result",
	"search-results",
	"search-row",
	"search-section",
	"second",
	"section-header",
	"section-header-icon",
	"section-header-text",
	"section-label",
	"section-link-text",
	"seek-indicator",
	"segmented",
	"segmented-control",
	"segmented-control-button",
	"segmented-control-highlight",
	"selected",
	"selected-img",
	"send-button",
	"series",
	"series-color",
	"series-item",
	"setsuki",
	"setting-btn",
	"settings",
	"settings-page",
	"severity-attention",
	"severity-caution",
	"severity-critical",
	"severity-information",
	"severity-success",
	"sheet-body",
	"sheet-container",
	"sheet-content",
	"sheet-filter-group",
	"sheet-filters",
	"sheet-header",
	"sheet-overlay",
	"shimmer-center",
	"show",
	"show-reasoning-container",
	"showing",
	"sidebar",
	"single-row",
	"size-max",
	"size-min",
	"size-standard",
	"skeleton-load",
	"skip-container",
	"slide",
	"slider",
	"slider-buffer-track",
	"slider-card",
	"slider-hover-preview",
	"slider-loading-track",
	"slider-rail",
	"slider-thumb",
	"slider-tick",
	"slider-tick-bar",
	"slider-tooltip",
	"slider-track",
	"slot-flyout-wrap",
	"small",
	"small-chip",
	"smoked",
	"solid",
	"song-externals",
	"song-metadata",
	"sonner-loader",
	"sonner-loading-bar",
	"sonner-loading-wrapper",
	"sonner-spinner",
	"sortable-drag",
	"sortable-ghost",
	"space-between",
	"spacer",
	"sparkle-1",
	"sparkle-2",
	"split-button",
	"split-button-chevron",
	"split-button-container",
	"spoiler",
	"star",
	"stat-box",
	"state",
	"stats-header",
	"status",
	"status-text",
	"status-text-container",
	"steps-container",
	"steps-row",
	"stickToBottom",
	"stroke",
	"style-accent",
	"style-hyperlink",
	"style-standard",
	"subtitle-canvas",
	"subtitles",
	"subtle",
	"suggested-anime-picture",
	"summary",
	"svelte-2y9sd",
	"svelte-8ss99",
	"svelte-dtuwq",
	"svelte-pxhcz",
	"svg",
	"swipe-page",
	"tab-switcher",
	"taking-test-container",
	"target-infobar",
	"target-row",
	"taste",
	"tasteScreen",
	"teaching-tip",
	"teaching-tip-anchor",
	"teaching-tip-backdrop",
	"teaching-tip-caret",
	"teaching-tip-close-button",
	"teaching-tip-content",
	"teaching-tip-footer",
	"teaching-tip-image",
	"teaching-tip-wrapper",
	"text",
	"text-area",
	"text-area-button",
	"text-area-buttons",
	"text-area-clear-button",
	"text-area-container",
	"text-area-underline",
	"text-block",
	"text-box",
	"text-box-button",
	"text-box-buttons",
	"text-box-clear-button",
	"text-box-container",
	"text-box-underline",
	"text-center",
	"text-container",
	"text-info",
	"text-input",
	"text-primary",
	"text-secondary",
	"text-shimmer",
	"text-tertiary",
	"textbox",
	"textboxes",
	"theme-upload-buttons",
	"thumb",
	"thumb-content",
	"tier",
	"tier-title",
	"tiers",
	"tile",
	"tile-skeleton",
	"time",
	"time-left",
	"title",
	"toast",
	"toggle-container",
	"toggle-switch",
	"toggle-switch-container",
	"tomolist-card",
	"tomolist-create-wrap",
	"toolbar",
	"tooltip",
	"tooltip-anchor",
	"tooltip-wrapper",
	"top",
	"top-messages",
	"top-strip",
	"topbar",
	"track",
	"transition-wrap",
	"transition-wrapper",
	"tv-announcement",
	"type-body",
	"type-body-large",
	"type-body-large-strong",
	"type-body-strong",
	"type-caption",
	"type-day",
	"type-display",
	"type-month-year",
	"type-subtitle",
	"type-title",
	"type-title-large",
	"unread",
	"use-mask",
	"value",
	"variant--default",
	"version",
	"vertical",
	"vertical-divider",
	"video-canvas",
	"video-preview",
	"view-months",
	"view-window",
	"view-years",
	"visible",
	"volume-flyout",
	"w2g-changepassword-wrap",
	"w2g-copyroomurl-wrap",
	"w2g-create-wrap",
	"watch-together",
	"web-results",
	"width",
	"windows",
	"wrap",
	"wrapper"
];

/** openani.me'nin CSS'inde geçen id'ler. */
export const SITE_IDS: string[] = [
	"about-dialog",
	"account",
	"anisub-logo",
	"auth",
	"avatar",
	"avatar-skeleton",
	"background",
	"badge",
	"banner",
	"banner-glow",
	"bars",
	"bottom",
	"box",
	"bullet",
	"buttons",
	"card",
	"change-avatar-decoration",
	"chip",
	"close-button",
	"content",
	"date",
	"description",
	"details-button",
	"download-manager",
	"download-setsuki",
	"emoji",
	"esenler-carousel",
	"esenler-holder",
	"fansub",
	"fansub-order-dialog",
	"giveaway-announcement-dialog-drawer",
	"google",
	"header",
	"hello-dialog",
	"icon",
	"image",
	"info",
	"item-text",
	"label",
	"logo",
	"logout-button",
	"lottie-player",
	"main",
	"mobile-announcement-dialog-drawer",
	"mobile-notification-drawer",
	"mobile-notification-setsuki",
	"name",
	"new-version-announcement-dialog-drawer",
	"notification-center",
	"notification-message",
	"notification-setsuki",
	"notification-title",
	"openanime-logo",
	"openanime-logo-wrap",
	"page",
	"play-button",
	"playlist",
	"poster",
	"pricing-decoration",
	"progress",
	"progress-text",
	"rating",
	"ratings",
	"replace",
	"search",
	"search-result",
	"setsuki",
	"side-info",
	"sliderHolder",
	"splash-screen",
	"star-1",
	"storage-usage",
	"summary",
	"title",
	"top",
	"user",
	"vals",
	"version-table"
];

/** Sitenin fds dışı custom property'leri. Stable API DEĞİL — çoğu
 *  Svelte scoped selector'lara bağlı ve her deploy'da değişebilir. */
export const SITE_VARS: string[] = [
	"--border-radius",
	"--chevron",
	"--contrast-text-shadow",
	"--error-bg",
	"--error-border",
	"--error-text",
	"--explore-card-width",
	"--explore-columns",
	"--glow-rotation",
	"--gradient-opacity",
	"--gradient-stop",
	"--gray1",
	"--gray10",
	"--gray11",
	"--gray12",
	"--gray2",
	"--gray3",
	"--gray4",
	"--gray5",
	"--gray6",
	"--gray7",
	"--gray8",
	"--gray9",
	"--info-bg",
	"--info-border",
	"--info-text",
	"--lift",
	"--lift-amount",
	"--mask-gradient",
	"--mask-radius",
	"--mask-radius-smooth",
	"--mask-x",
	"--mobile-offset",
	"--normal-bg",
	"--normal-border",
	"--normal-text",
	"--os-handle-bg",
	"--os-handle-bg-active",
	"--os-handle-bg-hover",
	"--os-handle-border",
	"--os-handle-border-active",
	"--os-handle-border-hover",
	"--os-handle-border-radius",
	"--os-handle-interactive-area-offset",
	"--os-handle-max-size",
	"--os-handle-min-size",
	"--os-handle-perpendicular-size",
	"--os-handle-perpendicular-size-active",
	"--os-handle-perpendicular-size-hover",
	"--os-padding-axis",
	"--os-padding-perpendicular",
	"--os-size",
	"--os-track-bg",
	"--os-track-bg-active",
	"--os-track-bg-hover",
	"--os-track-border",
	"--os-track-border-active",
	"--os-track-border-hover",
	"--os-track-border-radius",
	"--os-vah",
	"--os-vaw",
	"--scale",
	"--single-row-bleed-bottom",
	"--single-row-bleed-top",
	"--single-row-bleed-x",
	"--size",
	"--spacing",
	"--success-bg",
	"--success-border",
	"--success-text",
	"--toast-button-margin-end",
	"--toast-button-margin-start",
	"--toast-close-button-end",
	"--toast-close-button-start",
	"--toast-close-button-transform",
	"--toast-icon-margin-end",
	"--toast-icon-margin-start",
	"--toast-svg-margin-end",
	"--toast-svg-margin-start",
	"--vscode-foreground",
	"--vscode-panel-border",
	"--warning-bg",
	"--warning-border",
	"--warning-text",
	"--y"
];
